DROP TABLE IF EXISTS mpa CASCADE;
DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS genre CASCADE;
DROP TABLE IF EXISTS genres CASCADE;
DROP TABLE IF EXISTS film_genre CASCADE;
DROP TABLE IF EXISTS film_genres CASCADE;
DROP TABLE IF EXISTS film_likes CASCADE;
DROP TABLE IF EXISTS friends CASCADE;
DROP TABLE IF EXISTS friend_requests CASCADE;


CREATE TABLE IF NOT EXISTS mpa (
    mpa_id int generated by default as identity primary key,
    name varchar(255) not null
);

CREATE TABLE IF NOT EXISTS films (
    id int generated by default as identity primary key,
    name varchar(255) not null,
    description varchar(255) not null,
    release_date date not null,
    duration int not null,
    mpa_id int not null REFERENCES mpa (mpa_id)
);

CREATE TABLE IF NOT EXISTS users (
    id int generated by default as identity primary key,
    email varchar(255) not null,
    login varchar(255) not null,
    name varchar(255),
    birthday date not null
);

CREATE TABLE IF NOT EXISTS genre (
    genre_id int generated by default as identity primary key,
    name varchar(255) not null
);

CREATE TABLE IF NOT EXISTS film_genre (
    film_id int REFERENCES films (id),
    genre_id int REFERENCES genre (genre_id),
    primary key(film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS film_likes (
    film_id int REFERENCES films (id),
    user_id int REFERENCES users (id),
    primary key (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS friends (
    user_id int REFERENCES users (id),
    friend_id int REFERENCES users (id),
    primary key (user_id, friend_id)
);

